version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set version
          command: |
            make print-version | cat > version.txt
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker login -u i0nw -p $(echo ${DOCKERHUB_PASSWORD})
      - run:  docker build . -t i0nw/rust-wasm-builder:latest
      - run: docker tag i0nw/rust-wasm-builder:latest i0nw/rust-wasm-builder:$(cat version.txt)
      - run: |
          docker push i0nw/rust-wasm-builder:latest
          docker push i0nw/rust-wasm-builder:$(cat version.txt)
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
