version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set version
          command: |
            make print-version | cat > version.txt
            make print-branch | cat > branch.txt
            make print-rev | cat > rev.txt
            make print-build-user | cat > build-user.txt
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker login -u i0nw -p $(echo ${DOCKERHUB_PASSWORD})
      - run:  docker build . --build-arg DOCKER_ARG_VERSION=$(cat version.txt) --build-arg DOCKER_ARG_REV=$(cat rev.txt) --build-arg DOCKER_ARG_BRANCH=$(cat branch.txt) --build-arg DOCKER_ARG_BUILD_USER=$(cat build-user.txt) -t i0nw/http-file-server:latest
      - run: docker tag i0nw/rust-wasm-builder:latest i0nw/rust-wasm-builder:$(cat version.txt)
      - run: |
          docker push i0nw/rust-wasm-builder:latest
          docker push i0nw/rust-wasm-builder:$(cat version.txt)
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
